### ISSUE TITLE
Fix Jenkins auth for puppet

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga-build-vagrant#4]
Puppet will fail to create jobs in the current configuration, there a two possible solutions:
1. Update the config.xml to not have authorization
2. Create an authorized user puppet can use

**Comment by lazyfrosch** [comment]
Interesting discovery while talking to @b0e yesterday:

The cli_helper uses a SSH key stored at `$HOME/.ssh/id_rsa` by default.

We only would have to make sure to create the credential first in Jenkins.

**Comment by lazyfrosch** [comment]
The newer Jenkins brings default security, and adds an admin account.

I documented in README.md how to gain access for the first time.

Puppet creates a user for SSH access, when configured. Done in 6e113206431f46b0a08a7a0a2bf7fb11b31224e5
